export const root: string;
export const responsive: string;
export const map: string;
export const mapSwitch: string;
export const button: string;
export const basemapButton: string;
export const layerButton: string;
export const mapSwitchIcon: string;
export const input: string;
