// d3 tree example: https://codepen.io/sebilasse/pen/NWgOeXV?editors=1010
type SchemaLayerType = 'core'|'auto'|'bib';
interface SchemaDescription {
  '@id': string;
  '@type': 'rdfs:Class';
  'rdfs:subClassOf': string;
  layer: SchemaLayerType;
  name: string;
  description?: string;
  children?: SchemaDescription[];
}

/* TODO i18n */
export const descriptions: {[schemaName: string]: string} = {
   Thing: `The most generic type of item.`,
   Action: `An action performed by a direct agent and indirect participants upon a direct object …`,
   AchieveAction: `The act of accomplishing something via previous efforts. It is an instantaneous action rather than an ongoing process.`,
   LoseAction: `The act of being defeated in a competitive activity.`,
   TieAction: `The act of reaching a draw in a competitive activity.`,
   WinAction: `The act of achieving victory in a competitive activity.`,
   AssessAction: `The act of forming one's opinion, reaction or sentiment.`,
   ChooseAction: `The act of expressing a preference from a set of options or a large or unbounded set of choices/options.`,
   VoteAction: `The act of expressing a preference from a fixed/finite/structured set of choices/options.`,
   IgnoreAction: `The act of intentionally disregarding the object. An agent ignores an object.`,
   ReactAction: `The act of responding instinctively and emotionally to an object, expressing a sentiment.`,
   AgreeAction: `The act of expressing a consistency of opinion with the object …`,
   DisagreeAction: `The act of expressing a difference of opinion with the object …`,
   DislikeAction: `The act of expressing a negative sentiment about the object. An agent dislikes an object (a proposition, topic or theme) with participants.`,
   EndorseAction: `An agent approves/certifies/likes/supports/sanction an object.`,
   LikeAction: `The act of expressing a positive sentiment about the object. An agent likes an object (a proposition, topic or theme) with participants.`,
   WantAction: `The act of expressing a desire about the object. An agent wants an object.`,
   ReviewAction: `The act of producing a balanced opinion about the object for an audience …`,
   ConsumeAction: `The act of ingesting information/resources/food.`,
   DrinkAction: `The act of swallowing liquids.`,
   EatAction: `The act of swallowing solid objects.`,
   InstallAction: `The act of installing an application.`,
   ListenAction: `The act of consuming audio content.`,
   ReadAction: `The act of consuming written content.`,
   UseAction: `The act of applying an object to its intended purpose.`,
   WearAction: `The act of dressing oneself in clothing.`,
   ViewAction: `The act of consuming static visual content.`,
   WatchAction: `The act of consuming dynamic/moving visual content.`,
   ControlAction: `An agent controls a device or application.`,
   ActivateAction: `The act of starting or activating a device or application`,
   DeactivateAction: `The act of stopping or deactivating a device or application`,
   ResumeAction: `The act of resuming a device or application which was formerly paused`,
   SuspendAction: `The act of momentarily pausing a device or application (e.g. pause music playback or pause a timer).`,
   CreateAction: `The act of deliberately creating/producing/generating/building a result out of the agent.`,
   CookAction: `The act of producing/preparing food.`,
   DrawAction: `The act of producing a visual/graphical representation of an object, typically with a pen/pencil and paper as instruments.`,
   FilmAction: `The act of capturing sound and moving images on film, video, or digitally.`,
   PaintAction: `The act of producing a painting, typically with paint and canvas as instruments.`,
   PhotographAction: `The act of capturing still images of objects using a camera.`,
   WriteAction: `The act of authoring written creative content.`,
   FindAction: `The act of finding an object.Related actions:SearchAction: FindAction is generally lead by a SearchAction, but not necessarily.`,
   CheckAction: `An agent inspects/determines/investigates/inquire or examine an object's accuracy/quality/condition or state.`,
   DiscoverAction: `The act of discovering/finding an object.`,
   TrackAction: `An agent tracks an object for updates.Related actions:FollowAction: Unlike FollowAction, TrackAction refers to the interest
on the location of innanimates objects …`,
   InteractAction: `The act of interacting with another person or organization.`,
   BefriendAction: `The act of forming a personal connection with someone (object) mutually/bidirectionally/symmetrically …`,
   CommunicateAction: `The act of conveying information to another person via a communication medium (instrument) such as speech, email, or telephone conversation.`,
   AskAction: `The act of posing a question / favor to someone.Related actions:ReplyAction: Appears generally as a response to AskAction.`,
   CheckInAction: `The act of an agent communicating (service provider, social media, etc) their arrival by registering/confirming for a previously reserved service`,
   CheckOutAction: `The act of an agent communicating (service provider, social media, etc) their departure of a previously reserved service`,
   CommentAction: `The act of generating a comment about a subject.`,
   InformAction: `The act of notifying someone of information pertinent to them, with no expectation of a response.`,
   ConfirmAction: `The act of notifying someone that a future event/action is going to happen as expected …`,
   RsvpAction: `The act of notifying an event organizer as to whether you expect to attend the event.`,
   InviteAction: `The act of asking someone to attend an event. Reciprocal of RsvpAction.`,
   ReplyAction: `The act of responding to a question/message asked/sent by the object …`,
   ShareAction: `The act of distributing content to people for their amusement or edification.`,
   FollowAction: `The act of forming a personal connection with someone/something (object) unidirectionally/asymmetrically to get updates polled …`,
   JoinAction: `An agent joins an event/group with participants/friends at a location …`,
   LeaveAction: `An agent leaves an event / group with participants/friends at a location …`,
   MarryAction: `The act of marrying a person.`,
   RegisterAction: `The act of registering to be a user of a service, product or web page …`,
   SubscribeAction: `The act of forming a personal connection with someone/something (object) unidirectionally/asymmetrically to get updates pushed …`,
   UnRegisterAction: `The act of un-registering from a service.Related actions:RegisterAction: antonym of UnRegisterAction …`,
   MoveAction: `The act of an agent relocating to a place.Related actions:TransferAction: Unlike TransferAction, the subject of the move is a living
Person or Organization rather than an inanimate object.`,
   ArriveAction: `The act of arriving at a place. An agent arrives at a destination from an fromLocation, optionally with participants.`,
   DepartAction: `The act of departing from a place. An agent departs from an fromLocation for a destination, optionally with participants.`,
   TravelAction: `The act of traveling from an fromLocation to a destination by a specified mode of transport, optionally with participants.`,
   OrganizeAction: `The act of manipulating/administering/supervising/controlling one or more objects.`,
   AllocateAction: `The act of organizing tasks/objects/events by associating resources to it.`,
   AcceptAction: `The act of committing to/adopting an object.Related actions:RejectAction: The antonym of AcceptAction.`,
   AssignAction: `The act of allocating an action/event/task to some destination (someone or something).`,
   AuthorizeAction: `The act of granting permission to an object.`,
   RejectAction: `The act of rejecting to/adopting an object.Related actions:AcceptAction: The antonym of RejectAction.`,
   ApplyAction: `The act of registering to an organization/service without the guarantee to receive it …`,
   BookmarkAction: `An agent bookmarks/flags/labels/tags/marks an object.`,
   PlanAction: `The act of planning the execution of an event/task/action/reservation/plan to a future date.`,
   CancelAction: `The act of asserting that a future event/action is no longer going to happen …`,
   ReserveAction: `Reserving a concrete object.Related actions:ScheduleAction: Unlike ScheduleAction, ReserveAction reserves concrete objects`,
   ScheduleAction: `Scheduling future actions, events, or tasks.Related actions:ReserveAction: Unlike ReserveAction, ScheduleAction allocates future actions`,
   PlayAction: `The act of playing/exercising/training/performing for enjoyment, leisure, recreation, Competition or exercise …`,
   ExerciseAction: `The act of participating in exertive activity for the purposes of improving health and fitness.`,
   PerformAction: `The act of participating in performance arts.`,
   SearchAction: `The act of searching for an object.Related actions:FindAction: SearchAction generally leads to a FindAction, but not necessarily.`,
   TradeAction: `The act of participating in an exchange of goods and services for monetary compensation …`,
   BuyAction: `The act of giving money to a seller in exchange for goods or services rendered…`,
   DonateAction: `The act of providing goods, services, or money without compensation, often for philanthropic reasons.`,
   OrderAction: `An agent orders an object/product/service to be delivered/sent.`,
   PayAction: `An agent pays a price to a participant.`,
   QuoteAction: `An agent quotes/estimates/appraises an object/product/service with a price at a location/store.`,
   RentAction: `The act of giving money in return for temporary use, but not ownership, of an object such as a vehicle or property …`,
   SellAction: `The act of taking money from a buyer in exchange for goods or services rendered …`,
   TipAction: `The act of giving money voluntarily to a beneficiary in recognition of services rendered.`,
   TransferAction: `The act of transferring/moving (abstract or concrete) animate or inanimate objects from one place to another.`,
   BorrowAction: `The act of obtaining an object under an agreement to return it at a later date …`,
   DownloadAction: `The act of downloading an object.`,
   GiveAction: `The act of transferring ownership of an object to a destination …`,
   LendAction: `The act of providing an object under an agreement that it will be returned at a later date …`,
   ReceiveAction: `The act of physically/electronically taking delivery of an object thathas been transferred from an origin to a destination …`,
   ReturnAction: `The act of returning to the origin that which was previously received (concrete objects) or taken (ownership).`,
   SendAction: `The act of physically/electronically dispatching an object for transfer from an origin to a destination …`,
   TakeAction: `The act of gaining ownership of an object from an origin. Reciprocal of GiveAction …`,
   UpdateAction: `The act of managing by changing/editing the state of the object.`,
   AddAction: `The act of editing by adding an object to a collection.`,
   InsertAction: `The act of adding at a specific location in an ordered collection.`,
   AppendAction: `The act of inserting at the end if an ordered collection.`,
   PrependAction: `The act of inserting at the beginning if an ordered collection.`,
   DeleteAction: `The act of editing a recipient by removing one of its objects.`,
   ReplaceAction: `The act of editing a recipient by replacing an old object with a new object.`,
   CreativeWork: `The most generic kind of creative work, including books, movies, photographs, software programs, etc.`,
   Article: `An article, such as a news article or piece of investigative report …`,
   NewsArticle: `A news article.`,
   Report: `A Report generated by governmental or non-governmental organization.`,
   ScholarlyArticle: `A scholarly article.`,
   MedicalScholarlyArticle: `A scholarly article in the medical domain.`,
   SocialMediaPosting: `A post to a social media platform, including blog posts, tweets, Facebook posts, etc.`,
   BlogPosting: `A blog post.`,
   LiveBlogPosting: `A blog post intended to provide a rolling textual coverage of an ongoing event through continuous updates.`,
   DiscussionForumPosting: `A posting to a discussion forum.`,
   TechArticle: `A technical article - Example: How-to (task) topics, step-by-step, procedural troubleshooting, specifications, etc.`,
   APIReference: `Reference documentation for application programming interfaces (APIs).`,
   Atlas: `A collection or bound volume of maps, charts, plates or tables, physical or in media form illustrating any subject.`,
   Blog: `A blog.`,
   Book: `A book.`,
   Audiobook: `An audiobook.`,
   Chapter: `One of the sections into which a book is divided. A chapter usually has a section number or a name.`,
   Clip: `A short TV or radio program or a segment/part of a program.`,
   MovieClip: `A short segment/part of a movie.`,
   RadioClip: `A short radio program or a segment/part of a radio program.`,
   TVClip: `A short TV program or a segment/part of a TV program.`,
   VideoGameClip: `A short segment/part of a video game.`,
   Code: `Computer programming source code. Example: Full (compile ready) solutions, code snippet samples, scripts, templates.`,
   Collection: `A created collection of Creative Works or other artefacts.`,
   ComicStory: `The term "story" is any indivisible, re-printable unit of a comic, including the interior stories, covers, and backmatter …`,
   ComicCoverArt: `The artwork on the cover of a comic.`,
   Comment: `A comment on an item - for example, a comment on a blog post …`,
   Answer: `An answer offered to a question; perhaps correct, perhaps opinionated or wrong.`,
   CreativeWorkSeason: `A media season e.g. tv, radio, video game etc.`,
   RadioSeason: `Season dedicated to radio broadcast and associated online delivery.`,
   TVSeason: `Season dedicated to TV broadcast and associated online delivery.`,
   CreativeWorkSeries: `A CreativeWorkSeries in schema.org is a group of related items, typically but not necessarily of the same kind …`,
   BookSeries: `A series of books. Included books can be indicated with the hasPart property.`,
   MovieSeries: `A series of movies. Included movies can be indicated with the hasPart property.`,
   Periodical: `A publication in any medium issued in successive parts bearing numerical or chronological designations and intended, such as
a magazine, scholarly journal, or newspaper to continue indefinitely …`,
   ComicSeries: `A sequential publication of comic stories under a tunifying title, for example "The Amazing Spider-Man" or "Groo the Wanderer".`,
   Newspaper: `A publication containing information about varied topics that are pertinent to general information, a geographic area, or a specific subject matter`,
   RadioSeries: `CreativeWorkSeries dedicated to radio broadcast and associated online delivery.`,
   TVSeries: `CreativeWorkSeries dedicated to TV broadcast and associated online delivery.`,
   VideoGameSeries: `A video game series.`,
   DataCatalog: `A collection of datasets.`,
   Dataset: `A body of structured information describing some topic(s) of interest.`,
   DataFeed: `A single feed providing structured information about one or more entities or topics.`,
   Diet: `A strategy of regulating the intake of food to achieve or maintain a specific health-related goal.`,
   EmailMessage: `An email message.`,
   Episode: `A media episode (e.g. TV, radio, video game) which can be part of a series or season.`,
   RadioEpisode: `A radio episode which can be part of a series or season.`,
   TVEpisode: `A TV episode which can be part of a series or season.`,
   ExercisePlan: `Fitness-related activity designed for a specific health-related purpose, including defined exercise routines
as well as activity prescribed by a clinician.`,
   Game: `The Game type represents things which are games. These are typically rule-governed recreational activities …`,
   VideoGame: `A video game is an electronic game that involves human interaction with a user interface to generate visual feedback on a video device.`,
   Map: `A map.`,
   MediaObject: `An image, video, or audio object embedded in a web page. Note that a creative work may have many media objects associated with it on the same web page …`,
   AudioObject: `An audio file.`,
   DataDownload: `A dataset in downloadable form.`,
   ImageObject: `An image file.`,
   Barcode: `An image of a visual machine-readable code such as a barcode or QR code.`,
   MusicVideoObject: `A music video file.`,
   VideoObject: `A video file.`,
   Movie: `A movie.`,
   MusicComposition: `A musical composition.`,
   MusicPlaylist: `A collection of music tracks in playlist form.`,
   MusicAlbum: `A collection of music tracks.`,
   MusicRelease: `A MusicRelease is a specific release of a music album.`,
   MusicRecording: `A music recording (track), usually a single song.`,
   Painting: `A painting.`,
   Photograph: `A photograph.`,
   PublicationIssue: `A part of a successively published publication such as a periodical or publication volume, often numbered, usually containing
a grouping of works such as articles …`,
   ComicIssue: `Individual comic issues are serially published as part of a larger series …`,
   PublicationVolume: `A part of a successively published publication such as a periodical or multi-volume work, often numbered …`,
   Question: `A specific question - e.g. from a user seeking answers online, or collected in a Frequently Asked Questions (FAQ) document.`,
   Recipe: `A recipe.`,
   Review: `A review of an item - for example, of a restaurant, movie, or store.`,
   Sculpture: `A piece of sculpture.`,
   Season: `A media season e.g. tv, radio, video game etc.`,
   Series: `A Series in schema.org is a group of related items, typically but not necessarily of the same kind.`,
   SoftwareApplication: `A software application.`,
   MobileApplication: `A software application designed specifically to work well on a mobile device such as a telephone.`,
   WebApplication: `Web applications.`,
   SoftwareSourceCode: `Computer programming source code. Example: Full (compile ready) solutions, code snippet samples, scripts, templates.`,
   Thesis: `A thesis or dissertation document submitted in support of candidature for an academic degree or professional qualification.`,
   VisualArtwork: `A work of art that is primarily visual in character.`,
   CoverArt: `The artwork on the outer surface of a CreativeWork.`,
   WebPage: `A web page. Every web page is implicitly assumed to be declared to be of type WebPage, so the various properties about that webpage,
such as breadcrumb may be used …`,
   AboutPage: `Web page type: About page.`,
   CheckoutPage: `Web page type: Checkout page.`,
   CollectionPage: `Web page type: Collection page.`,
   ImageGallery: `Web page type: Image gallery page.`,
   VideoGallery: `Web page type: Video gallery page.`,
   ContactPage: `Web page type: Contact page.`,
   ItemPage: `A page devoted to a single item, such as a particular product or hotel.`,
   MedicalWebPage: `A web page that provides medical information.`,
   ProfilePage: `Web page type: Profile page.`,
   QAPage: `A QAPage is a WebPage focussed on a specific Question and its Answer(s), …`,
   SearchResultsPage: `Web page type: Search results page.`,
   WebPageElement: `A web page element, like a table or an image.`,
   SiteNavigationElement: `A navigation element of the page.`,
   Table: `A table on a Web page.`,
   WPAdBlock: `An advertising section of the page.`,
   WPFooter: `The footer section of the page.`,
   WPHeader: `The header section of the page.`,
   WPSideBar: `A sidebar section of the page.`,
   WebSite: `A WebSite is a set of related web pages and other items typically served from a single web domain and accessible via URLs.`,
   Event: `An event happening at a certain time and location, such as a concert, lecture, or festival …`,
   BusinessEvent: `Event type: Business event.`,
   ChildrensEvent: `Event type: Children's event.`,
   ComedyEvent: `Event type: Comedy event.`,
   DanceEvent: `Event type: A social dance.`,
   DeliveryEvent: `An event involving the delivery of an item.`,
   EducationEvent: `Event type: Education event.`,
   ExhibitionEvent: `Event type: Exhibition event, e.g. at a museum, library, archive, tradeshow, …`,
   Festival: `Event type: Festival.`,
   FoodEvent: `Event type: Food event.`,
   LiteraryEvent: `Event type: Literary event.`,
   MusicEvent: `Event type: Music event.`,
   PublicationEvent: `A PublicationEvent corresponds indifferently to the event of publication for a CreativeWork of any type …`,
   BroadcastEvent: `An over the air or online broadcast event.`,
   OnDemandEvent: `A publication event e.g. catch-up TV or radio podcast, during which a program is available on-demand.`,
   SaleEvent: `Event type: Sales event.`,
   ScreeningEvent: `A screening of a movie or other video.`,
   SocialEvent: `Event type: Social event.`,
   SportsEvent: `Event type: Sports event.`,
   TheaterEvent: `Event type: Theater performance.`,
   UserInteraction: `UserInteraction and its subtypes is an old way of talking about users interacting with pages …`,
   UserBlocks: `UserInteraction and its subtypes is an old way of talking about users interacting with pages …`,
   UserCheckins: `UserInteraction and its subtypes is an old way of talking about users interacting with pages …`,
   UserComments: `UserInteraction and its subtypes is an old way of talking about users interacting with pages …`,
   UserDownloads: `UserInteraction and its subtypes is an old way of talking about users interacting with pages …`,
   UserLikes: `UserInteraction and its subtypes is an old way of talking about users interacting with pages …`,
   UserPageVisits: `UserInteraction and its subtypes is an old way of talking about users interacting with pages …`,
   UserPlays: `UserInteraction and its subtypes is an old way of talking about users interacting with pages …`,
   UserPlusOnes: `UserInteraction and its subtypes is an old way of talking about users interacting with pages …`,
   UserTweets: `UserInteraction and its subtypes is an old way of talking about users interacting with pages …`,
   VisualArtsEvent: `Event type: Visual arts event.`,
   Intangible: `A utility class that serves as the umbrella for a number of 'intangible' things such as quantities, structured values, etc.`,
   AlignmentObject: `An intangible item that describes an alignment between a learning resource and a node in an educational framework.`,
   Audience: `Intended audience for an item, i.e. the group for whom the item was created.`,
   BusinessAudience: `A set of characteristics belonging to businesses, e.g. who compose an item's target audience.`,
   EducationalAudience: `An EducationalAudience.`,
   MedicalAudience: `Target audiences for medical web pages. Enumerated type.`,
   PeopleAudience: `A set of characteristics belonging to people, e.g. who compose an item's target audience.`,
   ParentAudience: `A set of characteristics describing parents, who can be interested in viewing some content.`,
   Brand: `A brand is a name used by an organization or business person for labeling a product, product group, or similar.`,
   BroadcastChannel: `A unique instance of a BroadcastService on a CableOrSatelliteService lineup.`,
   RadioChannel: `A unique instance of a radio BroadcastService on a CableOrSatelliteService lineup.`,
   TelevisionChannel: `A unique instance of a television BroadcastService on a CableOrSatelliteService lineup.`,
   BusTrip: `A trip on a commercial bus line.`,
   Class: `A class, also often called a 'Type'; equivalent to rdfs:Class.`,
   DataFeedItem: `A single item within a larger data feed.`,
   Demand: `A demand entity represents the public, not necessarily binding, not necessarily exclusive, announcement by an organization or person
to seek a certain type of goods or services …`,
   EntryPoint: `An entry point, within some Web-based protocol.`,
   Enumeration: `Lists or enumerations; for example, a list of cuisines or music genres, etc.`,
   ActionStatusType: `The status of an Action.`,
   BoardingPolicyType: `A type of boarding policy used by an airline.`,
   BookFormatType: `The publication format of the book.`,
   BusinessEntityType: `A business entity type is a conceptual entity representing the legal form, the size, the main line of business, the position
in the value chain, or any combination thereof, of an organization or business person …`,
   BusinessFunction: `The business function specifies the type of activity or access`,
   ContactPointOption: `Enumerated options related to a ContactPoint.`,
   DayOfWeek: `The day of the week, e.g. used to specify to which day the opening hours of an OpeningHoursSpecification refer …`,
   DeliveryMethod: `A delivery method is a standardized procedure for transferring the product or service to the destination of fulfillment chosen by the customer …`,
   LockerDelivery: `A DeliveryMethod in which an item is made available via locker.`,
   ParcelService: `A private parcel service as the delivery mode available for a certain offer …`,
   DrugCostCategory: `Enumerated categories of medical drug costs.`,
   DrugPregnancyCategory: `Categories that represent an assessment of the risk of fetal injury due to a drug or pharmaceutical used as directed
by the mother during pregnancy.`,
   DrugPrescriptionStatus: `Indicates whether this drug is available by prescription or over-the-counter.`,
   EventStatusType: `EventStatusType is an enumeration type whose instances represent several states that an Event may be in.`,
   GamePlayMode: `Indicates whether this game is multi-player, co-op or single-player.`,
   GameServerStatus: `Status of a game server.`,
   InfectiousAgentClass: `Classes of agents or pathogens that transmit infectious diseases …`,
   ItemAvailability: `A list of possible product availability options.`,
   ItemListOrderType: `Enumerated for values for itemListOrder for indicating how an ordered ItemList is organized.`,
   MapCategoryType: `An enumeration of several kinds of Map.`,
   MedicalDevicePurpose: `Categories of medical devices, organized by the purpose or intended use of the device.`,
   MedicalEnumeration: `Enumerations related to health and the practice of medicine.`,
   MedicalEvidenceLevel: `Level of evidence for a medical guideline. Enumerated type.`,
   MedicalImagingTechnique: `Any medical imaging modality typically used for diagnostic purposes …`,
   MedicalObservationalStudyDesign: `Design models for observational medical studies. Enumerated type.`,
   MedicalProcedureType: `An enumeration that describes different types of medical procedures.`,
   MedicalSpecialty: `Any specific branch of medical science or practice. Medical specialities include clinical specialties that pertain to
particular organ systems and their respective disease states, as well as allied health specialties …`,
   MedicalStudyStatus: `The status of a medical study. Enumerated type.`,
   MedicalTrialDesign: `Design models for medical trials. Enumerated type.`,
   MedicineSystem: `Systems of medical practice.`,
   PhysicalActivityCategory: `Categories of physical activity, organized by physiologic classification.`,
   PhysicalExam: `A type of physical examination of a patient performed by a physician …`,
   MusicAlbumProductionType: `Classification of the album by it's type of content: soundtrack, live album, studio album, etc.`,
   MusicAlbumReleaseType: `The kind of release which this album is: single, EP or album.`,
   MusicReleaseFormatType: `Format of this release (the type of recording media used.`,
   OfferItemCondition: `A list of possible conditions for the item.`,
   OrderStatus: `Enumerated status values for Order.`,
   PaymentMethod: `A payment method is a standardized procedure for transferring the monetary amount for a purchase …`,
   CreditCard: `A credit or debit card type as a standardized procedure for transferring the monetary amount for a purchase …`,
   PaymentStatusType: `A specific payment status. For example, PaymentDue, PaymentComplete, etc.`,
   QualitativeValue: `A predefined value for a product characteristic, e.g. the power cord plug type "US" or the garment sizes "S", "M", "L", and "XL".`,
   CarUsageType: `A value indicating a special usage of a car, e.g. commercial rental, driving school, or as a taxi.`,
   DriveWheelConfigurationValue: `A value indicating which roadwheels will receive torque.`,
   SteeringPositionValue: `A value indicating a steering position.`,
   ReservationStatusType: `Enumerated status values for Reservation.`,
   RsvpResponseType: `RsvpResponseType is an enumeration type whose instances represent responding to an RSVP request.`,
   Specialty: `Any branch of a field in which people typically develop specific expertise, usually after significant study, time, and effort.`,
   WarrantyScope: `A range of of services that will be provided to a customer free of charge in case of a defect or malfunction of a product …`,
   Flight: `An airline flight.`,
   GameServer: `Server that provides game interaction in a multiplayer game.`,
   Invoice: `A statement of the money due for goods or services; a bill.`,
   ItemList: `A list of items of any sort; for example, Top 10 Movies About Weathermen, or Top 100 Party Songs …`,
   BreadcrumbList: `A BreadcrumbList is an ItemList consisting of a chain of linked Web pages, typically described using at least their URL and their name,
and typically ending with the current page …`,
   OfferCatalog: `An OfferCatalog is an ItemList that contains related Offers and/or further OfferCatalogs that are offeredBy the same provider.`,
   JobPosting: `A listing that describes a job opening in a certain organization.`,
   Language: `Natural languages such as Spanish, Tamil, Hindi, English, etc …`,
   ListItem: `An list item, e.g. a step in a checklist or how-to description.`,
   Offer: `An offer to transfer some rights to an item or to provide a service; for example, an offer to sell tickets to an event,
to rent the DVD of a movie, to stream a TV show over the internet, to repair a motorcycle, or to loan a book …`,
   AggregateOffer: `When a single product is associated with multiple offers (for example, the same pair of shoes is offered by different merchants),
then AggregateOffer can be used.`,
   Order: `An order is a confirmation of a transaction (a receipt), which can contain multiple line items, each represented by an Offer that has been accepted
by the customer.`,
   OrderItem: `An order item is a line of an order. It includes the quantity and shipping details of a bought offer.`,
   ParcelDelivery: `The delivery of a parcel either via the postal service or a commercial service.`,
   Permit: `A permit issued by an organization, e.g. a parking pass.`,
   GovernmentPermit: `A permit issued by a government agency.`,
   ProgramMembership: `Used to describe membership in a loyalty programs (e.g. "StarAliance"), traveler clubs`,
   Property: `A property, used to indicate attributes and relationships of some Thing; equivalent to rdf:Property.`,
   PropertyValueSpecification: `A Property value specification.`,
   Quantity: `Quantities such as distance, time, mass, weight, etc. Particular instances of say Mass are entities like '3 Kg' or '4 milligrams'.`,
   Distance: `Properties that take Distances as values are of the form "Number" Length unit of measure"'…`,
   Duration: `Quantity: Duration (use ISO 8601 duration format).`,
   Energy: `Properties that take Energy as values are of the form "Number" Energy unit of measure"'.`,
   Mass: `Properties that take Mass as values are of the form "Number" Mass unit of measure"'…`,
   Rating: `A rating is an evaluation on a numeric scale, such as 1 to 5 stars.`,
   AggregateRating: `The average rating based on multiple ratings or reviews.`,
   Reservation: `Describes a reservation for travel, dining or an event. Some reservations require tickets.`,
   BusReservation: `A reservation for bus travel.`,
   EventReservation: `A reservation for an event like a concert, sporting event, or lecture.`,
   FlightReservation: `A reservation for air travel.`,
   FoodEstablishmentReservation: `A reservation to dine at a food-related business.`,
   LodgingReservation: `A reservation for lodging at a hotel, motel, inn, etc.`,
   RentalCarReservation: `A reservation for a rental car.`,
   ReservationPackage: `A group of multiple reservations with common values for all sub-reservations.`,
   TaxiReservation: `A reservation for a taxi.`,
   TrainReservation: `A reservation for train travel.`,
   Role: `Represents additional information about a relationship or property…`,
   OrganizationRole: `A subclass of Role used to describe roles within organizations.`,
   EmployeeRole: `A subclass of OrganizationRole used to describe employee relationships.`,
   PerformanceRole: `A PerformanceRole is a Role that some entity places with regard to a theatrical performance, e…`,
   Seat: `Used to describe a seat, such as a reserved seat in an event reservation.`,
   Service: `A service provided by an organization, e.g. delivery service, print services, etc.`,
   BroadcastService: `A delivery service through which content is provided via broadcast over the air or online.`,
   CableOrSatelliteService: `A service which provides access to media programming like TV or radio…`,
   GovernmentService: `A service provided by a government organization, e.g. food stamps, veterans benefits, etc.`,
   Taxi: `A taxi.`,
   TaxiService: `A service for a vehicle for hire with a driver for local travel…`,
   ServiceChannel: `A means for accessing a service, e.g. a government office location, web site, or phone number.`,
   StructuredValue: `Structured values are used when the value of a property has a more complex structure than simply being a textual value
or a reference to another thing.`,
   ContactPoint: `A contact point; for example, a Customer Complaints department.`,
   PostalAddress: `The mailing address.`,
   DatedMoneySpecification: `A DatedMoneySpecification represents monetary values with optional start and end dates …`,
   EngineSpecification: `Information about the engine of the vehicle. A vehicle can have multiple engines represented by multiple engine specification entities.`,
   GeoCoordinates: `The geographic coordinates of a place or event.`,
   GeoShape: `The geographic shape of a place. A GeoShape can be described using several properties whose values are based on latitude/longitude pairs …`,
   GeoCircle: `A GeoCircle is a GeoShape representing a circular geographic area …`,
   InteractionCounter: `A summary of how users have interacted with this CreativeWork …`,
   NutritionInformation: `Nutritional information about the recipe.`,
   OpeningHoursSpecification: `A structured value providing information about the opening hours of a place or a certain service inside a place.`,
   OwnershipInfo: `A structured value providing information about when a certain organization or person owned a certain product.`,
   PriceSpecification: `A structured value representing a monetary amount. Typically, only the subclasses of this type are used for markup.`,
   DeliveryChargeSpecification: `The price for the delivery of an offer using a particular delivery method.`,
   PaymentChargeSpecification: `The costs of settling the payment using a particular payment method.`,
   UnitPriceSpecification: `The price asked for a given offer by the respective organization or person.`,
   PropertyValue: `A property-value pair, e.g. representing a feature of a product or place …`,
   QuantitativeValue: `A point value or interval for product characteristics and other purposes.`,
   TypeAndQuantityNode: `A structured value indicating the quantity, unit of measurement, and business function of goods included in a bundle offer.`,
   WarrantyPromise: `A structured value representing the duration and scope of services that will be provided to a customer free of charge
in case of a defect or malfunction of a product.`,
   Ticket: `Used to describe a ticket to an event, a flight, a bus ride, etc.`,
   TrainTrip: `A trip on a commercial train line.`,
   MedicalEntity: `The most generic type of entity related to health and the practice of medicine.`,
   AnatomicalStructure: `Any part of the human body, typically a component of an anatomical system …`,
   Bone: `Rigid connective tissue that comprises up the skeletal structure of the human body.`,
   BrainStructure: `Any anatomical structure which pertains to the soft nervous tissue functioning as the coordinating center
of sensation and intellectual and nervous activity.`,
   Joint: `The anatomical location at which two or more bones make contact.`,
   Ligament: `A short band of tough, flexible, fibrous connective tissue that functions to connect multiple bones, cartilages, and structurally support joints.`,
   Muscle: `A muscle is an anatomical structure consisting of a contractile form of tissue that animals use to effect movement.`,
   Nerve: `A common pathway for the electrochemical nerve impulses that are transmitted along each of the axons.`,
   Vessel: `A component of the human body circulatory system comprised of an intricate network of hollow tubes that transport blood throughout the entire body.`,
   Artery: `A type of blood vessel that specifically carries blood away from the heart.`,
   LymphaticVessel: `A type of blood vessel that specifically carries lymph fluid unidirectionally toward the heart.`,
   Vein: `A type of blood vessel that specifically carries blood to the heart.`,
   AnatomicalSystem: `An anatomical system is a group of anatomical structures that work together to perform a certain task …`,
   MedicalCause: `The causative agent(s) that are responsible for the pathophysiologic process that eventually results in a medical condition,
symptom or sign …`,
   MedicalCondition: `Any condition of the human body that affects the normal functioning of a person, whether physically or mentally …`,
   InfectiousDisease: `An infectious disease is a clinically evident human disease resulting from the presence of pathogenic microbial agents,
like pathogenic viruses, pathogenic bacteria, fungi, protozoa, multicellular parasites, and prions …`,
   MedicalContraindication: `A condition or factor that serves as a reason to withhold a certain medical therapy …`,
   MedicalDevice: `Any object used in a medical capacity, such as to diagnose or treat a patient.`,
   MedicalGuideline: `Any recommendation made by a standard society (e.g. ACC/AHA) or consensus statement that denotes how to diagnose
and treat a particular condition …`,
   MedicalGuidelineContraindication: `A guideline contraindication that designates a process as harmful and where quality of the
data supporting the contraindication is sound.`,
   MedicalGuidelineRecommendation: `A guideline recommendation that is regarded as efficacious and where quality of the data supporting
the recommendation is sound.`,
   MedicalIndication: `A condition or factor that indicates use of a medical therapy, including signs, symptoms, risk factors,
anatomical states, etc.`,
   ApprovedIndication: `An indication for a medical therapy that has been formally specified or approved by a regulatory body that
regulates use of the therapy; for example, the US FDA approves indications for most drugs in the US.`,
   PreventionIndication: `An indication for preventing an underlying condition, symptom, etc.`,
   TreatmentIndication: `An indication for treating an underlying condition, symptom, etc.`,
   MedicalIntangible: `A utility class that serves as the umbrella for a number of 'intangible' things in the medical space.`,
   DDxElement: `An alternative, closely-related condition typically considered later in the differential diagnosis process along with the
signs that are used to distinguish it.`,
   DoseSchedule: `A specific dosing schedule for a drug or supplement.`,
   MaximumDoseSchedule: `The maximum dosing schedule considered safe for a drug or supplement as recommended by an authority or by the
drug/supplement's manufacturer …`,
   RecommendedDoseSchedule: `A recommended dosing schedule for a drug or supplement as prescribed or recommended by an authority or by the
drug/supplement's manufacturer …`,
   ReportedDoseSchedule: `A patient-reported or observed dosing schedule for a drug or supplement.`,
   DrugCost: `The cost per unit of a medical drug. Note that this type is not meant to represent the price in an offer of a drug for sale;
see the Offer type for that …`,
   DrugLegalStatus: `The legal availability status of a medical drug.`,
   DrugStrength: `A specific strength in which a medical drug is available in a specific country.`,
   MedicalCode: `A code for a medical entity.`,
   MedicalConditionStage: `A stage of a medical condition, such as 'Stage IIIa'.`,
   MedicalProcedure: `A process of care used in either a diagnostic, therapeutic, or palliative capacity that relies on invasive (surgical),
non-invasive, or percutaneous techniques.`,
   DiagnosticProcedure: `A medical procedure intended primarily for diagnostic, as opposed to therapeutic, purposes.`,
   PalliativeProcedure: `A medical procedure intended primarily for palliative purposes, aimed at relieving the symptoms of an underlying
health condition.`,
   TherapeuticProcedure: `A medical procedure intended primarily for therapeutic purposes, aimed at improving a health condition.`,
   MedicalRiskEstimator: `Any rule set or interactive tool for estimating the risk of developing a complication or condition.`,
   MedicalRiskCalculator: `A complex mathematical calculation requiring an online calculator, used to assess prognosis …`,
   MedicalRiskScore: `A simple system that adds up the number of risk factors to yield a score that is associated with prognosis, …`,
   MedicalRiskFactor: `A risk factor is anything that increases a person's likelihood of developing or contracting a disease, medical condition,
or complication.`,
   MedicalSignOrSymptom: `Any indication of the existence of a medical condition or disease.`,
   MedicalSign: `Any physical manifestation of a person's medical condition discoverable by objective diagnostic tests or physical examination.`,
   MedicalSymptom: `Any indication of the existence of a medical condition or disease that is apparent to the patient.`,
   MedicalStudy: `A medical study is an umbrella type covering all kinds of research studies relating to human medicine or health,
including observational studies and interventional trials and registries, randomized, controlled or not …`,
   MedicalObservationalStudy: `An observational study is a type of medical study that attempts to infer the possible effect of a treatment
through observation of a cohort of subjects over a period of time …`,
   MedicalTrial: `A medical trial is a type of medical study that uses scientific process used to compare the safety and efficacy
of medical therapies or medical procedures …`,
   MedicalTest: `Any medical test, typically performed for diagnostic purposes.`,
   BloodTest: `A medical test performed on a sample of a patient's blood.`,
   ImagingTest: `Any medical imaging modality typically used for diagnostic purposes.`,
   MedicalTestPanel: `Any collection of tests commonly ordered together.`,
   PathologyTest: `A medical test performed by a laboratory that typically involves examination of a tissue sample by a pathologist.`,
   MedicalTherapy: `Any medical intervention designed to prevent, treat, and cure human diseases and medical conditions, including both curative
and palliative therapies …`,
   DietarySupplement: `A product taken by mouth that contains a dietary ingredient intended to supplement the diet …`,
   Drug: `A chemical or biologic substance, used as a medical therapy, that has a physiological effect on an organism.`,
   DrugClass: `A class of medical drugs, e.g., statins. Classes can represent general pharmacological class, common mechanisms of action,
common physiological effects, etc.`,
   LifestyleModification: `A process of care involving exercise, changes to diet, fitness routines, and other lifestyle changes aimed at
improving a health condition.`,
   PhysicalActivity: `Any bodily activity that enhances or maintains physical fitness and overall health and wellness …`,
   PhysicalTherapy: `A process of progressive physical care and rehabilitation aimed at improving a health condition.`,
   PsychologicalTreatment: `A process of care relying upon counseling, dialogue, communication, verbalization aimed at
improving a mental health condition.`,
   RadiationTherapy: `A process of care using radiation aimed at improving a health condition.`,
   SuperficialAnatomy: `Anatomical features that can be observed by sight (without dissection), including the form and proportions
of the human body as well as surface landmarks that correspond to deeper subcutaneous structures …`,
   Organization: `An organization such as a school, NGO, corporation, club, etc.`,
   Airline: `An organization that provides flights for passengers.`,
   Corporation: `Organization: A business corporation.`,
   EducationalOrganization: `An educational organization.`,
   CollegeOrUniversity: `A college, university, or other third-level educational institution.`,
   ElementarySchool: `An elementary school.`,
   HighSchool: `A high school.`,
   MiddleSchool: `A middle school (typically for children aged around 11-14, although this varies somewhat).`,
   Preschool: `A preschool.`,
   School: `A school.`,
   GovernmentOrganization: `A governmental organization or agency.`,
   LocalBusiness: `A particular physical business or branch of an organization. Examples of LocalBusiness include a restaurant,
a particular branch of a restaurant chain, a branch of a bank, a medical practice, a club, a bowling alley, etc.`,
   AnimalShelter: `Animal shelter.`,
   AutomotiveBusiness: `Car repair, sales, or parts.`,
   AutoBodyShop: `Auto body shop.`,
   AutoDealer: `An car dealership.`,
   AutoPartsStore: `An auto parts store.`,
   AutoRental: `A car rental business.`,
   AutoRepair: `Car repair business.`,
   AutoWash: `A car wash business.`,
   GasStation: `A gas station.`,
   MotorcycleDealer: `A motorcycle dealer.`,
   MotorcycleRepair: `A motorcycle repair shop.`,
   ChildCare: `A Childcare center.`,
   DryCleaningOrLaundry: `A dry-cleaning business.`,
   EmergencyService: `An emergency service, such as a fire station or ER.`,
   FireStation: `A fire station. With firemen.`,
   Hospital: `A hospital.`,
   PoliceStation: `A police station.`,
   EmploymentAgency: `An employment agency.`,
   EntertainmentBusiness: `A business providing entertainment.`,
   AdultEntertainment: `An adult entertainment establishment.`,
   AmusementPark: `An amusement park.`,
   ArtGallery: `An art gallery.`,
   Casino: `A casino.`,
   ComedyClub: `A comedy club.`,
   MovieTheater: `A movie theater.`,
   NightClub: `A nightclub or discotheque.`,
   FinancialService: `Financial services business.`,
   AccountingService: `Accountancy business. As a LocalBusiness it can be described as a provider of one or more Service(s).`,
   AutomatedTeller: `ATM/cash machine.`,
   BankOrCreditUnion: `Bank or credit union.`,
   InsuranceAgency: `An Insurance agency.`,
   FoodEstablishment: `A food-related business.`,
   Bakery: `A bakery.`,
   BarOrPub: `A bar or pub.`,
   Brewery: `Brewery.`,
   CafeOrCoffeeShop: `A cafe or coffee shop.`,
   FastFoodRestaurant: `A fast-food restaurant.`,
   IceCreamShop: `An ice cream shop.`,
   Restaurant: `A restaurant.`,
   Winery: `A winery.`,
   GovernmentOffice: `A government office; for example, an IRS or DMV office.`,
   PostOffice: `A post office.`,
   HealthAndBeautyBusiness: `Health and beauty.`,
   BeautySalon: `Beauty salon.`,
   DaySpa: `A day spa.`,
   HairSalon: `A hair salon.`,
   HealthClub: `A health club.`,
   NailSalon: `A nail salon.`,
   TattooParlor: `A tattoo parlor.`,
   HomeAndConstructionBusiness: `A construction business. A HomeAndConstructionBusiness is a LocalBusiness that provides services around
homes and buildings …`,
   Electrician: `An electrician.`,
   GeneralContractor: `A general contractor.`,
   HVACBusiness: `A business that provide Heating, Ventilation and Air Conditioning services.`,
   HousePainter: `A house painting service.`,
   Locksmith: `A locksmith.`,
   MovingCompany: `A moving company.`,
   Plumber: `A plumbing service.`,
   RoofingContractor: `A roofing contractor.`,
   InternetCafe: `An internet cafe.`,
   LegalService: `A LegalService is a business that provides legally-oriented services, advice and representation …`,
   Attorney: `Professional service: Attorney. This type is deprecated - LegalService is more inclusive and less ambiguous.`,
   Notary: `A notary.`,
   Library: `A library.`,
   LodgingBusiness: `A lodging business, such as a motel, hotel, or inn.`,
   BedAndBreakfast: `Bed and breakfast.`,
   Hostel: `A hostel - cheap accommodation, often in shared dormitories.`,
   Hotel: `A hotel.`,
   Motel: `A motel.`,
   MedicalOrganization: `A medical organization, such as a doctor's office or clinic.`,
   Dentist: `A dentist.`,
   DiagnosticLab: `A medical laboratory that offers on-site or off-site diagnostic services.`,
   MedicalClinic: `A medical clinic.`,
   Optician: `A store that sells reading glasses and similar devices for improving vision.`,
   Pharmacy: `A pharmacy or drugstore.`,
   Physician: `A doctor's office.`,
   VeterinaryCare: `A vet's office.`,
   ProfessionalService: `Original definition: "provider of professional services."
The general ProfessionalService type for local businesses was deprecated due to confusion with Service …`,
   RadioStation: `A radio station.`,
   RealEstateAgent: `A real-estate agent.`,
   RecyclingCenter: `A recycling center.`,
   SelfStorage: `A self-storage facility.`,
   ShoppingCenter: `A shopping center or mall.`,
   SportsActivityLocation: `A sports location, such as a playing field.`,
   BowlingAlley: `A bowling alley.`,
   ExerciseGym: `A gym.`,
   GolfCourse: `A golf course.`,
   PublicSwimmingPool: `A public swimming pool.`,
   SkiResort: `A ski resort.`,
   SportsClub: `A sports club.`,
   StadiumOrArena: `A stadium.`,
   TennisComplex: `A tennis complex.`,
   Store: `A retail good store.`,
   BikeStore: `A bike store.`,
   BookStore: `A bookstore.`,
   ClothingStore: `A clothing store.`,
   ComputerStore: `A computer store.`,
   ConvenienceStore: `A convenience store.`,
   DepartmentStore: `A department store.`,
   ElectronicsStore: `An electronics store.`,
   Florist: `A florist.`,
   FurnitureStore: `A furniture store.`,
   GardenStore: `A garden store.`,
   GroceryStore: `A grocery store.`,
   HardwareStore: `A hardware store.`,
   HobbyShop: `A store that sells materials useful or necessary for various hobbies.`,
   HomeGoodsStore: `A home goods store.`,
   JewelryStore: `A jewelry store.`,
   LiquorStore: `A shop that sells alcoholic drinks such as wine, beer, whisky and other spirits.`,
   MensClothingStore: `A men's clothing store.`,
   MobilePhoneStore: `A store that sells mobile phones and related accessories.`,
   MovieRentalStore: `A movie rental store.`,
   MusicStore: `A music store.`,
   OfficeEquipmentStore: `An office equipment store.`,
   OutletStore: `An outlet store.`,
   PawnShop: `A shop that will buy, or lend money against the security of, personal possessions.`,
   PetStore: `A pet store.`,
   ShoeStore: `A shoe store.`,
   SportingGoodsStore: `A sporting goods store.`,
   TireShop: `A tire shop.`,
   ToyStore: `A toy store.`,
   WholesaleStore: `A wholesale store.`,
   TelevisionStation: `A television station.`,
   TouristInformationCenter: `A tourist information center.`,
   TravelAgency: `A travel agency.`,
   NGO: `Organization: Non-governmental Organization.`,
   PerformingGroup: `A performance group, such as a band, an orchestra, or a circus.`,
   DanceGroup: `A dance group; for example, the Alvin Ailey Dance Theater or Riverdance.`,
   MusicGroup: `A musical group, such as a band, an orchestra, or a choir. Can also be a solo musician.`,
   TheaterGroup: `A theater group or company, for example, the Royal Shakespeare Company or Druid Theatre.`,
   SportsOrganization: `Represents the collection of all sports organizations, including sports teams, governing bodies, and sports associations.`,
   SportsTeam: `Organization: Sports team.`,
   Person: `A person (alive, dead, undead, or fictional).`,
   Place: `Entities that have a somewhat fixed, physical extension.`,
   AdministrativeArea: `A geographical region, typically under the jurisdiction of a particular government.`,
   City: `A city or town.`,
   Country: `A country.`,
   State: `A state or province of a country.`,
   CivicStructure: `A public structure, such as a town hall or concert hall.`,
   Airport: `An airport.`,
   Aquarium: `Aquarium.`,
   Beach: `Beach.`,
   Bridge: `A bridge.`,
   BusStation: `A bus station.`,
   BusStop: `A bus stop.`,
   Campground: `A campground.`,
   Cemetery: `A graveyard.`,
   Crematorium: `A crematorium.`,
   EventVenue: `An event venue.`,
   GovernmentBuilding: `A government building.`,
   CityHall: `A city hall.`,
   Courthouse: `A courthouse.`,
   DefenceEstablishment: `A defence establishment, such as an army or navy base.`,
   Embassy: `An embassy.`,
   LegislativeBuilding: `A legislative building; for example, the state capitol.`,
   Museum: `A museum.`,
   MusicVenue: `A music venue.`,
   Park: `A park.`,
   ParkingFacility: `A parking lot or other parking facility.`,
   PerformingArtsTheater: `A theater or other performing art center.`,
   PlaceOfWorship: `Place of worship, such as a church, synagogue, or mosque.`,
   BuddhistTemple: `A Buddhist temple.`,
   CatholicChurch: `A Catholic church.`,
   Church: `A church.`,
   HinduTemple: `A Hindu temple.`,
   Mosque: `A mosque.`,
   Synagogue: `A synagogue.`,
   Playground: `A playground.`,
   RVPark: `A place offering space for "Recreational Vehicles", Caravans, mobile homes and the like.`,
   SubwayStation: `A subway station.`,
   TaxiStand: `A taxi stand.`,
   TrainStation: `A train station.`,
   Zoo: `A zoo.`,
   Landform: `A landform or physical feature.
Landform elements include mountains, plains, lakes, rivers, seascape and oceanic waterbody interface features such as bays, peninsulas, seas and so forth,
including sub-aqueous terrain features such as submersed mountain ranges, volcanoes, and the great ocean basins.`,
   BodyOfWater: `A body of water, such as a sea, ocean, or lake.`,
   Canal: `A canal, like the Panama Canal.`,
   LakeBodyOfWater: `A lake (for example, Lake Pontrachain).`,
   OceanBodyOfWater: `An ocean (for example, the Pacific).`,
   Pond: `A pond.`,
   Reservoir: `A reservoir of water, typically an artificially created lake, like the Lake Kariba reservoir.`,
   RiverBodyOfWater: `A river (for example, the broad majestic Shannon).`,
   SeaBodyOfWater: `A sea (for example, the Caspian sea).`,
   Waterfall: `A waterfall, like Niagara.`,
   Continent: `One of the continents (for example, Europe or Africa).`,
   Mountain: `A mountain, like Mount Whitney or Mount Everest.`,
   Volcano: `A volcano, like Fuji san.`,
   LandmarksOrHistoricalBuildings: `An historical landmark or building.`,
   Residence: `The place where a person lives.`,
   ApartmentComplex: `Residence type: Apartment complex.`,
   GatedResidenceCommunity: `Residence type: Gated community.`,
   SingleFamilyResidence: `Residence type: Single-family home.`,
   TouristAttraction: `A tourist attraction.`,
   Product: `Any offered product or service. For example: a pair of shoes; a concert ticket; the rental of a car; a haircut;
or an episode of a TV show streamed online.`,
   IndividualProduct: `A single, identifiable product instance (e.g. a laptop with a particular serial number).`,
   ProductModel: `A datasheet or vendor specification of a product (in the sense of a prototypical description).`,
   SomeProducts: `A placeholder for multiple similar products of the same kind.`,
   Vehicle: `A vehicle is a device that is designed or used to transport people or cargo over land, water, air, or through space.`,
   BusOrCoach: `A bus (also omnibus or autobus) is a road vehicle designed to carry passengers …`,
   Car: `A car is a wheeled, self-powered motor vehicle used for transportation.`,
   Motorcycle: `A motorcycle or motorbike is a single-track, two-wheeled motor vehicle.`,
   MotorizedBicycle: `A motorized bicycle is a bicycle with an attached motor used to power the vehicle, or to assist with pedaling.`
};

const compactedChildren = [
  ['Action',0,[
    ['AchieveAction',0,['LoseAction','TieAction','WinAction']],
    ['AssessAction',0,[
      ['ChooseAction',0,['VoteAction']],
      'IgnoreAction',
      ['ReactAction',0,['AgreeAction','DisagreeAction','DislikeAction','EndorseAction','LikeAction','WantAction']],
      'ReviewAction'
    ]],
    ['ConsumeAction',0,['DrinkAction','EatAction','InstallAction','ListenAction','ReadAction',['UseAction',0,['WearAction']],'ViewAction','WatchAction']],
    ['ControlAction',0,['ActivateAction','DeactivateAction','ResumeAction','SuspendAction']],
    ['CreateAction',0,['CookAction','DrawAction','FilmAction','PaintAction','PhotographAction','WriteAction']],
    ['FindAction',0,['CheckAction','DiscoverAction','TrackAction']],
    ['InteractAction',0,[
      'BefriendAction',
      ['CommunicateAction',0,[
        'AskAction',
        'CheckInAction',
        'CheckOutAction',
        'CommentAction',
        ['InformAction',0,['ConfirmAction','RsvpAction']],
        'InviteAction',
        'ReplyAction',
        'ShareAction'
      ]],
      'FollowAction',
      'JoinAction',
      'LeaveAction',
      'MarryAction',
      'RegisterAction',
      'SubscribeAction',
      'UnRegisterAction'
    ]],
    ['MoveAction',0,['ArriveAction','DepartAction','TravelAction']],
    ['OrganizeAction',0,[
      ['AllocateAction',0,['AcceptAction','AssignAction','AuthorizeAction','RejectAction']],
      'ApplyAction',
      'BookmarkAction',
      ['PlanAction',0,['CancelAction','ReserveAction','ScheduleAction']]
    ]],
    ['PlayAction',0,['ExerciseAction','PerformAction']],
    'SearchAction',
    ['TradeAction',0,['BuyAction','DonateAction','OrderAction','PayAction','QuoteAction','RentAction','SellAction','TipAction']],
    ['TransferAction',0,['BorrowAction','DownloadAction','GiveAction','LendAction','ReceiveAction','ReturnAction','SendAction','TakeAction']],
    ['UpdateAction',0,[['AddAction',0,[['InsertAction',0,['AppendAction','PrependAction']]]],'DeleteAction','ReplaceAction']]
  ]],
  ['CreativeWork',0,[
    ['Article',0,[
      'NewsArticle',
      'Report',
      ['ScholarlyArticle',0,['MedicalScholarlyArticle']],
      ['SocialMediaPosting',0,[['BlogPosting',0,['LiveBlogPosting']],'DiscussionForumPosting']],
      ['TechArticle',0,['APIReference']]
    ]],
    ['Atlas',2],
    'Blog',
    ['Book',0,[['Audiobook',2]]],
    ['Chapter',2],
    ['Clip',0,['MovieClip','RadioClip','TVClip','VideoGameClip']],
    'Code',
    ['Collection',2],
    ['ComicStory',2,[['ComicCoverArt',2]]],
    ['Comment',0,['Answer']],
    ['CreativeWorkSeason',0,['RadioSeason','TVSeason']],
    ['CreativeWorkSeries',0,['BookSeries','MovieSeries',['Periodical',0,[['ComicSeries',2],['Newspaper',2]]],'RadioSeries','TVSeries','VideoGameSeries']],
    'DataCatalog',
    ['Dataset',0,['DataFeed']],
    'Diet',
    'EmailMessage',
    ['Episode',0,['RadioEpisode','TVEpisode']],
    'ExercisePlan',
    ['Game',0,['VideoGame']],
    'Map',
    ['MediaObject',0,['AudioObject','DataDownload',['ImageObject',0,['Barcode']],'MusicVideoObject','VideoObject']],
    'Movie',
    'MusicComposition',
    ['MusicPlaylist',0,['MusicAlbum','MusicRelease']],
    'MusicRecording',
    'Painting',
    'Photograph',
    ['PublicationIssue',0,[['ComicIssue',2]]],
    'PublicationVolume',
    'Question',
    'Recipe',
    'Review',
    'Sculpture',
    'Season',
    'Series',
    ['SoftwareApplication',0,['MobileApplication','WebApplication']],
    'SoftwareSourceCode',
    ['Thesis',2],
    ['VisualArtwork',0,[['CoverArt',2]]],
    ['WebPage',0,[
      'AboutPage',
      'CheckoutPage',
      ['CollectionPage',0,['ImageGallery','VideoGallery']],
      'ContactPage',
      'ItemPage',
      'MedicalWebPage',
      'ProfilePage',
      'QAPage',
      'SearchResultsPage'
    ]],
    ['WebPageElement',0,['SiteNavigationElement','Table','WPAdBlock','WPFooter','WPHeader','WPSideBar']],
    'WebSite'
  ]],
  ['Event',0,[
    'BusinessEvent',
    'ChildrensEvent',
    'ComedyEvent',
    'DanceEvent',
    'DeliveryEvent',
    'EducationEvent',
    'ExhibitionEvent',
    'Festival',
    'FoodEvent',
    'LiteraryEvent',
    'MusicEvent',
    ['PublicationEvent',0,['BroadcastEvent','OnDemandEvent']],
    'SaleEvent',
    'ScreeningEvent',
    'SocialEvent',
    'SportsEvent',
    'TheaterEvent',
    ['UserInteraction',0,['UserBlocks','UserCheckins','UserComments','UserDownloads','UserLikes','UserPageVisits','UserPlays','UserPlusOnes','UserTweets']],
    'VisualArtsEvent'
  ]],
  ['Intangible',0,[
    'AlignmentObject',
    ['Audience',0,['BusinessAudience','EducationalAudience','MedicalAudience',['PeopleAudience',0,['ParentAudience']]]],
    'Brand',
    ['BroadcastChannel',0,['RadioChannel','TelevisionChannel']],
    'BusTrip',
    'Class',
    'DataFeedItem',
    'Demand',
    'EntryPoint',
    ['Enumeration',0,[
      'ActionStatusType',
      'BoardingPolicyType',
      'BookFormatType',
      'BusinessEntityType',
      'BusinessFunction',
      'ContactPointOption',
      'DayOfWeek',
      ['DeliveryMethod',0,['LockerDelivery','ParcelService']],
      'DrugCostCategory',
      'DrugPregnancyCategory',
      'DrugPrescriptionStatus',
      'EventStatusType',
      'GamePlayMode',
      'GameServerStatus',
      'InfectiousAgentClass',
      'ItemAvailability',
      'ItemListOrderType',
      'MapCategoryType',
      'MedicalDevicePurpose',
      ['MedicalEnumeration',0,[
        'MedicalEvidenceLevel',
        'MedicalImagingTechnique',
        'MedicalObservationalStudyDesign',
        'MedicalProcedureType',
        'MedicalSpecialty',
        'MedicalStudyStatus',
        'MedicalTrialDesign',
        'MedicineSystem',
        'PhysicalActivityCategory',
        'PhysicalExam'
      ]],
      'MusicAlbumProductionType',
      'MusicAlbumReleaseType',
      'MusicReleaseFormatType',
      'OfferItemCondition',
      'OrderStatus',
      ['PaymentMethod',0,['CreditCard']],
      'PaymentStatusType',
      ['QualitativeValue',0,['CarUsageType','DriveWheelConfigurationValue','SteeringPositionValue']],
      'ReservationStatusType',
      'RsvpResponseType',
      'Specialty',
      'WarrantyScope'
    ]],
    'Flight',
    'GameServer',
    'Invoice',
    ['ItemList',0,['BreadcrumbList','OfferCatalog']],
    'JobPosting',
    'Language',
    'ListItem',
    ['Offer',0,['AggregateOffer']],
    'Order',
    'OrderItem',
    'ParcelDelivery',
    ['Permit',0,['GovernmentPermit']],
    'ProgramMembership',
    'Property',
    'PropertyValueSpecification',
    ['Quantity',0,['Distance','Duration','Energy','Mass']],
    ['Rating',0,['AggregateRating']],
    ['Reservation',0,[
      'BusReservation',
      'EventReservation',
      'FlightReservation',
      'FoodEstablishmentReservation',
      'LodgingReservation',
      'RentalCarReservation',
      'ReservationPackage',
      'TaxiReservation',
      'TrainReservation'
    ]],
    ['Role',0,[['OrganizationRole',0,['EmployeeRole']],'PerformanceRole']],
    'Seat',
    ['Service',0,['BroadcastService','CableOrSatelliteService','GovernmentService','Taxi','TaxiService']],
    'ServiceChannel',
    ['StructuredValue',0,[
      ['ContactPoint',0,['PostalAddress']],
      'DatedMoneySpecification',
      'EngineSpecification',
      'GeoCoordinates',
      ['GeoShape',0,['GeoCircle']],
      'InteractionCounter',
      'NutritionInformation',
      'OpeningHoursSpecification',
      'OwnershipInfo',
      ['PriceSpecification',0,['DeliveryChargeSpecification','PaymentChargeSpecification','UnitPriceSpecification']],
      'PropertyValue',
      'QuantitativeValue',
      'TypeAndQuantityNode',
      'WarrantyPromise'
    ]],
    'Ticket',
    'TrainTrip'
  ]],
  ['MedicalEntity',0,[
    ['AnatomicalStructure',0,['Bone','BrainStructure','Joint','Ligament','Muscle','Nerve',['Vessel',0,['Artery','LymphaticVessel','Vein']]]],
    'AnatomicalSystem',
    'MedicalCause',
    ['MedicalCondition',0,['InfectiousDisease']],
    'MedicalContraindication',
    'MedicalDevice',
    ['MedicalGuideline',0,['MedicalGuidelineContraindication','MedicalGuidelineRecommendation']],
    ['MedicalIndication',0,['ApprovedIndication','PreventionIndication','TreatmentIndication']],
    ['MedicalIntangible',0,[
      'DDxElement',
      ['DoseSchedule',0,['MaximumDoseSchedule','RecommendedDoseSchedule','ReportedDoseSchedule']],
      'DrugCost',
      'DrugLegalStatus',
      'DrugStrength',
      'MedicalCode',
      'MedicalConditionStage'
    ]],
    ['MedicalProcedure',0,['DiagnosticProcedure','PalliativeProcedure','TherapeuticProcedure']],
    ['MedicalRiskEstimator',0,['MedicalRiskCalculator','MedicalRiskScore']],
    'MedicalRiskFactor',
    ['MedicalSignOrSymptom',0,['MedicalSign','MedicalSymptom']],
    ['MedicalStudy',0,['MedicalObservationalStudy','MedicalTrial']],
    ['MedicalTest',0,['BloodTest','ImagingTest','MedicalTestPanel','PathologyTest']],
    ['MedicalTherapy',0,[
      'DietarySupplement',
      'Drug',
      'DrugClass',
      ['LifestyleModification',0,['PhysicalActivity']],
      'PhysicalTherapy',
      'PsychologicalTreatment',
      'RadiationTherapy'
    ]],
    'SuperficialAnatomy'
  ]],
  ['Organization',0,[
    'Airline',
    'Corporation',
    ['EducationalOrganization',0,['CollegeOrUniversity','ElementarySchool','HighSchool','MiddleSchool','Preschool','School']],
    'GovernmentOrganization',
    ['LocalBusiness',0,[
      'AnimalShelter',
      ['AutomotiveBusiness',0,['AutoBodyShop','AutoDealer','AutoPartsStore','AutoRental','AutoRepair','AutoWash','GasStation','MotorcycleDealer','MotorcycleRepair']],
      'ChildCare',
      'DryCleaningOrLaundry',
      ['EmergencyService',0,['FireStation','Hospital','PoliceStation']],
      'EmploymentAgency',
      ['EntertainmentBusiness',0,['AdultEntertainment','AmusementPark','ArtGallery','Casino','ComedyClub','MovieTheater','NightClub']],
      ['FinancialService',0,['AccountingService','AutomatedTeller','BankOrCreditUnion','InsuranceAgency']],
      ['FoodEstablishment',0,['Bakery','BarOrPub','Brewery','CafeOrCoffeeShop','FastFoodRestaurant','IceCreamShop','Restaurant','Winery']],
      ['GovernmentOffice',0,['PostOffice']],
      ['HealthAndBeautyBusiness',0,['BeautySalon','DaySpa','HairSalon','HealthClub','NailSalon','TattooParlor']],
      ['HomeAndConstructionBusiness',0,['Electrician','GeneralContractor','HVACBusiness','HousePainter','Locksmith','MovingCompany','Plumber','RoofingContractor']],
      'InternetCafe',
      ['LegalService',0,['Attorney','Notary']],
      'Library',
      ['LodgingBusiness',0,['BedAndBreakfast','Hostel','Hotel','Motel']],
      ['MedicalOrganization',0,['Dentist','DiagnosticLab','MedicalClinic','Optician','Pharmacy','Physician','VeterinaryCare']],
      'ProfessionalService',
      'RadioStation',
      'RealEstateAgent',
      'RecyclingCenter',
      'SelfStorage',
      'ShoppingCenter',
      ['SportsActivityLocation',0,['BowlingAlley','ExerciseGym','GolfCourse','PublicSwimmingPool','SkiResort','SportsClub','StadiumOrArena','TennisComplex']],
      ['Store',0,[
        'BikeStore','BookStore','ClothingStore','ComputerStore','ConvenienceStore','DepartmentStore','ElectronicsStore','Florist','FurnitureStore','GardenStore',
        'GroceryStore','HardwareStore','HobbyShop','HomeGoodsStore','JewelryStore','LiquorStore','MensClothingStore','MobilePhoneStore','MovieRentalStore',
        'MusicStore','OfficeEquipmentStore','OutletStore','PawnShop','PetStore','ShoeStore','SportingGoodsStore','TireShop','ToyStore','WholesaleStore'
      ]],
      'TelevisionStation',
      'TouristInformationCenter',
      'TravelAgency'
    ]],
    'NGO',
    ['PerformingGroup',0,['DanceGroup','MusicGroup','TheaterGroup']],
    ['SportsOrganization',0,['SportsTeam']]
  ]],
  'Person',
  ['Place',0,[
    ['AdministrativeArea',0,['City','Country','State']],
    ['CivicStructure',0,[
      'Airport',
      'Aquarium',
      'Beach',
      'Bridge',
      'BusStation',
      'BusStop',
      'Campground',
      'Cemetery',
      'Crematorium',
      'EventVenue',
      ['GovernmentBuilding',0,['CityHall','Courthouse','DefenceEstablishment','Embassy','LegislativeBuilding']],
      'Museum',
      'MusicVenue',
      'Park',
      'ParkingFacility',
      'PerformingArtsTheater',
      ['PlaceOfWorship',0,['BuddhistTemple','CatholicChurch','Church','HinduTemple','Mosque','Synagogue']],
      'Playground',
      'RVPark',
      'SubwayStation',
      'TaxiStand',
      'TrainStation',
      'Zoo'
    ]],
    ['Landform',0,[
      ['BodyOfWater',0,['Canal','LakeBodyOfWater','OceanBodyOfWater','Pond','Reservoir','RiverBodyOfWater','SeaBodyOfWater','Waterfall']],
      'Continent',
      'Mountain',
      'Volcano'
    ]],
    'LandmarksOrHistoricalBuildings',
    ['Residence',0,['ApartmentComplex','GatedResidenceCommunity','SingleFamilyResidence']],
    'TouristAttraction'
  ]],
  ['Product',0,[
    'IndividualProduct','ProductModel','SomeProducts',['Vehicle',0,[['BusOrCoach',1],'Car',['Motorcycle',1],['MotorizedBicycle',1]]]
  ]]
];

export const schemaJsonLDContext = {
  'rdfs': 'http://www.w3.org/2000/01/rdf-schema#',
  'schema': 'http://schema.org/',
  'rdfs:subClassOf': {'@type':'@id'},
  name: 'rdfs:label',
  description: 'rdfs:comment',
  children: {'@reverse':'rdfs:subClassOf'}
};

const baseSchema = {
  '@context': schemaJsonLDContext,
  '@id': 'schema:Thing',
  '@type': 'rdfs:Class',
  name: 'Thing',
  description: 'The most generic type of item.',
  layer: 'core'
};
const layers: SchemaLayerType[] = ['core', 'auto', 'bib'];
function expand(children: any[], subClassOf = 'Thing'): SchemaDescription[] {
  return children.map((a: string | any[]) => {
    const [name = a, layerNr = 0, subChildren = []] = Array.isArray(a) ? a : [];
    const o: SchemaDescription = {
      '@type': 'rdfs:Class',
      '@id': `schema:${a[0]}`,
      'rdfs:subClassOf': `schema:${subClassOf}`,
      name,
      layer: layers[layerNr]
    }
    if (descriptions.hasOwnProperty(name)) {
      o.description = descriptions[name];
    }
    if (!!subChildren.length) {
      o.children = expand(subChildren, name)
    }
    return o
  })
}

const schemaOntology = { ...baseSchema, children: expand(compactedChildren) };
export default schemaOntology;
