export const root: string;
export const max3: string;
export const more3: string;
export const bookmark: string;
export const tag: string;
export const topic: string;
export const tagLink: string;
export const ribbon: string;
export const onlyHover: string;
