export const root: string;
export const row: string;
export const micro: string;
export const xs: string;
export const s: string;
export const m: string;
export const l: string;
export const xl: string;
export const xxl: string;
