export const root: string;
export const fold: string;
export const foldInput: string;
export const item: string;
export const foldItem: string;
export const icon: string;
export const name: string;
export const marker: string;
export const markerIcon: string;
