export const root: string;
export const dedicated: string;
export const no: string;
export const smokeWrapper: string;
export const separated: string;
export const isolated: string;
export const smoke: string;
export const smokededicated: string;
export const outside: string;
