const messages = {
  representative: 'repräsentative',
  org: 'Organisationen',
  url: 'URLs',
  cat: 'Kategorien',
  res: 'Reaktionen',
  notes: 'Notizen',

  bday: 'Geburtsdatum',
  anniversary: 'Geburtstag',
  tz: 'Zeitzone',
  callsign: 'Stationskennung',
  jobTitle: 'Berufsbezeichnung',
  role: 'Rolle',
  rev: 'Revision',

  mf_name: 'Der komplette/formatierte Name einer Person oder Organisation',
  'mf_honorific-prefix': 'z.B. Frau, Herr oder Dr.',
  'mf_given-name': 'Vorname',
  'mf_additional-name': 'Anderer/mittlerer Name',
  'mf_family-name': 'Nachname',
  'mf_sort-string': 'Zeichenkette um zu sortieren',
  'mf_honorific-suffix': 'z.B. Ph.D, Esq.',
  mf_nickname: 'Spitzname/Alias/Deckname',
  mf_email: 'eMail Adresse',
  mf_logo: 'Ein Logo, daß die Person oder Organisation repräsentiert',
  mf_photo: 'Ein Foto, daß die Person oder Organisation repräsentiert',
  mf_url: 'Homepage',
  mf_uid: 'Universell eindeutiger Identifikator, normalerweise eine kanonische URL',
  mf_category: 'Kategorie/Tag',
  mf_adr: 'Post Adresse, optional eingebettet in einer `h-adr`',
  'mf_post-office-box': 'Ein Postfach (P.O. Box)',
  'mf_street-address': 'Straße und Hausnummer',
  'mf_extended-address': 'Apartement/Suite/Zimmer-Name/-Nummer falls vorhanden',
  mf_locality: 'Stadt/Dorf/Ort',
  mf_region: 'Bundesland/Kanton/Provinz',
  'mf_postal-code': 'Postleitzahl, PLZ',
  'mf_country-name': 'Ländername',
  mf_label: 'Adress-Etikett',
  mf_geo: 'Geografische Informationen, optional eingebettet in einer `h-geo`',
  mf_latitude: 'Dezimaler Breitengrad',
  mf_longitude: 'Dezimaler Längengrad',
  mf_altitude: 'Dezimale Höhenlage',
  mf_tel: 'Telefonnummer',
  mf_note: 'Notizen',
  'mf_bday': 'Geburtsdatum',
  mf_anniversary: 'Geburtstag',
  mf_key: 'Kryptografisch öffentlicher Schlüssel, z.B. SSH or GPG',
  mf_org: 'Angegliederte Organisation, optional eingebettet in einer `h-card`',
  'mf_job-title': 'Berufsbezeichnung, ehemals `title` in h-card, eindeutig.',
  mf_role: 'Beschreibung der Rolle',
  mf_impp: 'Instant Messaging per RFC4770, neu in vCard4 (RFC 6350)',
  mf_sex: 'Biologisches Geschlecht, neu in vCard4 (RFC 6350)',
  'mf_gender-identity': 'Geschlechtsidentität, neu in vCard4 (RFC 6350)',
  mf_tz: 'Zeitzonenunterschied',
  mf_callsign: 'Stationskennung',
  mf_rev: 'Revision'
};

export default messages;
