export default {
	calendar: 'Kalendar',
	adrContact: 'Adresse & Kontakt',
	map: 'Karte',
	images: 'Bilder',
	locationmap: 'Veranstaltungsort',
	moreInfo: 'Weiterführende Informationen',
	amenity_restaurant: 'Restaurant',
	amenity_cafe: 'Café',
	amenity_fast_food: 'Schnellrestaurant, Snackbar, Sandwichbar oder ähnliches',
	amenity_bar: 'Bar',
	amenity_pub: 'Kneipe',
	amenity_ice_cream: 'Eisdiele',
	amenity_biergarten: 'Biergarten (im traditionellen Sinne)',
	leisure_outdoor_seating: 'Ein Sitzplatz im Freien, in der Regel für den Verzehr von Speisen und Getränken aus benachbarten Cafés und Restaurants',
	tourism_artwork: 'Kunstwerk',
	amenity_community_centre: 'Gemeindezentrum',
	amenity_library: 'Bibliothek',
	tourism_museum: 'Museum',
	amenity_theatre: 'Theater',
	amenity_cinema: 'Kino',
	amenity_nightclub: 'Nachtclub',
	amenity_arts_centre: 'Kunstzentrum',
	tourism_gallery: 'Kunstgalerie, Kunstmuseum',
	amenity_internet_cafe: 'Internetcafé',
	amenity_casino: 'Kasino',
	amenity_public_bookcase: 'Öffentliches Bücherregal',
	leisure_amusement_arcade: 'Eine Spielstätte mit kostenpflichtigen Spielen',
	historic_memorial: 'Denkmal (Standardgröße)',
	historic_archaeological_site: 'Ort, an dem Objekte von historischem Interesse aufbewahrt werden',
	historic_wayside_shrine: 'Historischer Schrein',
	historic_monument: 'Denkmal',
	historic_castle: 'Burg',
	historic_fort: 'Militärhistorisches Fort',
	historic_city_gate: 'Stadttor',
	man_made_obelisk: 'Obelisk',
	leisure_playground: 'Spielplatz',
	leisure_golf_course: 'Golfplatz',
	shop_massage: 'Massagesalon',
	leisure_sauna: 'Sauna',
	amenity_public_bath: 'Öffentliches Bad',
	leisure_miniature_golf: 'Minigolfplatz',
	leisure_beach_resort: 'Ein bewirtschafteter Strand',
	leisure_fishing: 'Ein öffentlicher Ort zum Angeln',
	leisure_bowling_alley: 'Bowling-Center',
	leisure_dog_park: 'Hundepark',
	golf_pin: 'Loch eines Golfplatzes',
	amenity_toilets: 'Öffentliche Toiletten',
	amenity_recycling: 'Wertstoffcontainer oder Wertstoffhof',
	amenity_waste_basket: 'Papierkorb',
	amenity_waste_disposal: 'Entsorgungsbehälter (mittlere Größe)',
	amenity_bench: 'Sitzbank',
	amenity_shelter: 'Unterstand (z. B. Wetterschutz)',
	amenity_drinking_water: 'Trinkwasser, Sprudler, Trinkbrunnen',
	tourism_picnic_site: 'Picknickplatz',
	amenity_fountain: 'Brunnen (Erholungs-/Dekorationsbrunnen)',
	tourism_camp_site: 'Zeltplatz, Campingplatz',
	leisure_picnic_table: 'Picknicktisch',
	tourism_caravan_site: 'Wohnwagenplatz, Wohnwagenpark, Wohnmobilstellplatz',
	amenity_bbq: 'Grillplatz',
	amenity_shower: 'Dusche',
	leisure_firepit: 'Feuerstelle',
	leisure_bird_hide: 'Vogelhäuschen',
	tourism_viewpoint: 'Aussichtspunkt',
	tourismus_hotel: 'Hotel',
	tourism_guest_house: 'Gästehaus',
	tourism_hostel: 'Herberge',
	tourism_chalet: 'Chalet (Ferienhaus)',
	tourismus_motel: 'Motel',
	tourism_apartment: 'Wohnung',
	tourism_alpine_hut: 'Almhütte',
	tourism_wilderness_hut: 'Wildnis-Hütte',
	amenity_bank: 'Bank',
	amenity_atm: 'Geldautomat oder Bankautomat',
	amenity_bureau_de_change: 'Wechselstube',
	amenity_pharmacy: 'Apotheke',
	amenity_hospital: 'Krankenhaus (stationäre Behandlung)',
	amenity_dentist: 'Zahnarzt',
	amenity_veterinary: 'Tierarzt',
	amenity_post_box: 'Briefkasten',
	amenity_post_office: 'Postamt',
	amenity_telephone: 'Öffentliches Telefon',
	emergency_phone: 'Notruftelefon',
	amenity_parking: 'Autoparkplatz',
	highway_bus_stop: 'Bushaltestelle',
	amenity_fuel: 'Tankstelle oder ähnliches',
	amenity_bicycle_parking: 'Fahrradabstellplatz',
	amenity_bus_station: 'Busbahnhof',
	aeroway_helipad: 'Hubschrauberlandeplatz',
	aeroway_aerodrome: 'Flughafen',
	amenity_bicycle_rental: 'Fahrradabstell-/Verleihstation',
	leisure_slipway: 'Slipanlage für Boote',
	amenity_taxi: 'Taxistand',
	railway_subway_entrance: 'Eingang zur U-Bahn',
	amenity_charging_station: 'Ladestation',
	highway_elevator: 'Aufzug',
	amenity_car_rental: 'Auto mieten',
	amenity_ferry_terminal: 'Fährhafen',
	amenity_motorcycle_parking: 'Motorradparkplatz',
	amenity_bicycle_repair_station: 'Fahrrad-Reparaturwerkstatt',
	amenity_boat_rental: 'Bootsverleih',
	oneway_yes: 'Einbahnstraße',
	barrier_gate: 'Schranke',
	highway_traffic_signals: 'Verkehrsampel',
	barrier_cycle_barrier: 'Schranken für den Fahrradverkehr',
	barrier_stile: 'Zaunpfahl',
	highway_mini_roundabout: 'Minikreisverkehr',
	barrier_toll_booth: 'Mautstelle',
	barrier_cattle_grid: 'Rindergitter',
	barrier_kissing_gate: 'Eine Schranke, die den Durchgang von Menschen, aber nicht von Vieh erlaubt',
	'barrier_full-height_turnstile': 'Ein Drehkreuz mit voller Höhe',
	barrier_motorcycle_barrier: 'Motorradschranke',
	waterway_dam: 'Damm',
	waterway_weir: 'Wehr',
	waterway_lock_gate: 'Tor einer Schleuse',
	natural_tree: 'Baum',
	natural_peak: 'Spitze, Gipfel, etc.',
	natural_spring: 'Quelle',
	natural_cave_entrance: 'Höhleneingang',
	waterway_waterfall: 'Wasserfall',
	natural_saddle: 'Topografischer Sattel',
	natural_volcano: 'Vulkan',
	amenity_police: 'Polizeistation',
	amenity_townhall: 'Rathaus',
	amenity_fire_station: 'Feuerwache',
	amenity_social_facility: 'Soziale Einrichtung',
	amenity_courthouse: 'Gerichtsgebäude',
	amenity_prison: 'Gefängnis',
	amenity_marketplace: 'Marktplatz',
	shop_convenience: 'Verbrauchermarkt',
	shop_supermarket: 'Supermarkt',
	shop_hairdresser: 'Friseursalon / Barbiersalon',
	shop_bakery: 'Bäckerei',
	shop_car_repair: 'Autoreparaturdienst',
	shop_car: 'Autogeschäft',
	shop_beauty: 'Schönheitsdienstleistungen außer Friseur',
	amenity_car_wash: 'Autowaschanlage',
	shop_butcher: 'Fleischer',
	shop_furniture: 'Einrichtungshaus',
	shop_florist: 'Blumenladen',
	shop_mobile_phone: 'Geschäft für Mobiltelefone und Zubehör',
	shop_electronics: 'Geschäft für Unterhaltungselektronik',
	shop_shoes: 'Schuhgeschäft',
	shop_car_parts: 'Autoteile-Geschäft',
	shop_optician: 'Optiker',
	shop_books: 'Buchhandlung',
	shop_gift: 'Geschenk- oder Souvenirladen',
	shop_department_store: 'Kaufhaus',
	shop_bicycle: 'Fahrradgeschäft, Einzelhandel, Reparatur und/oder Verleih',
	shop_variety_store: 'Kaufhaus',
	shop_travel_agency: 'Reisebüro',
	shop_sports: 'Geschäft für Sportartikel',
	shop_chemist: 'Apotheke',
	shop_computer: 'Computergeschäft',
	shop_stationery: 'Schreibwarengeschäft',
	shop_pet: 'Haustiergeschäft',
	shop_beverages: 'Getränkeladen',
	shop_tyres: 'Reifengeschäft',
	shop_motorcycle: 'Motorradgeschäft',
	shop_garden_centre: 'Gartencenter',
	shop_copyshop: 'Kopierladen',
	shop_toys: 'Spielzeugladen',
	shop_deli: 'Geschäft für Feinkost (Gourmet-Lebensmittel)',
	shop_tobacco: 'Tabakwarengeschäft',
	shop_seafood: 'Geschäft, das Fisch und/oder Meeresfrüchte verkauft',
	shop_interior_decoration: 'Geschäft, das Innendekorationen verkauft',
	shop_ticket: 'Geschäft, das Eintrittskarten für Konzerte, Veranstaltungen, öffentliche Verkehrsmittel verkauft',
	shop_photo: 'Fotogeschäft oder Fotostudio',
	shop_outdoor: 'Geschäft, das Outdoor-Ausrüstung verkauft',
	shop_houseware: 'Geschäft, das Haushaltswaren verkauft',
	shop_art: 'Kunstgeschäft',
	shop_paint: 'Geschäft, das Farben verkauft',
	shop_fabric: 'Geschäft, das Stoffe verkauft',
	shop_bookmaker: 'BuchhändlerIn',
	shop_second_hand: 'Geschäft, das Gebrauchtwaren verkauft',
	shop_charity: 'Geschäft für wohltätige Zwecke',
	shop_bed: 'Geschäft, das Matratzen verkauft',
	shop_medical_supply: 'Ein Geschäft, in dem man medizinische Geräte kaufen kann',
	shop_hifi: 'Geschäft für Hi-Fi-Anlagen',
	shop_music: 'Geschäft, das Musikaufnahmen verkauft',
	shop_coffee: 'Kaffeegeschäft',
	shop_musical_instrument: 'Geschäft, das Musikinstrumente verkauft',
	shop_tea: 'Teeladen',
	shop_video: 'Geschäft, das Videos/DVDs verkauft oder vermietet',
	shop_bag: 'Geschäft, das Taschen verkauft',
	shop_carpet: 'Geschäft, das Teppiche verkauft',
	shop_video_games: 'Geschäft, das Videospiele verkauft',
	amenity_vehicle_inspection: 'Staatliche Fahrzeuginspektion (z.B. TÜV,DEKRA)',
	shop_dairy: 'Geschäft, das Molkereiprodukte verkauft',
	office: 'Amt, Abteilung, Büro (alle)',
	man_made_tower: 'Turm im Allgemeinen',
	amenity_hunting_stand: 'Jagdstand',
	man_made_water_tower: 'Wasserturm',
	man_made_mast: 'Mast im Allgemeinen',
	military_bunker: 'Bunker',
	man_made_chimney: 'Schornstein',
	man_made_lighthouse: 'Leuchtturm',
	advertising_column: 'Litfaßsäule',
	man_made_crane: 'Kran (stationär)',
	man_made_windmill: 'Windmühle',
	man_made_communications_tower: 'Großer Turm zur Übertragung von Funkanwendungen',
	power_tower: 'Großer Strommast, der Hochspannungsleitungen trägt',
	power_pole: 'Kleiner Strommast, der Niederspannungs-Stromkabel trägt',
	place_city: 'Stadt',
	capital: 'Hauptstadt',
	entrance_yes: 'Eingang (Ausgang) eines Gebäudes',
	entrance_main: 'Haupteingang (-ausgang) eines Gebäudes',
	entrance_service: 'Ein Hintereingang eines Gebäudes',
	parkingSubtle: 'Parken auf der Fahrbahn / Parken neben der Fahrbahn',
	parkingU: 'Tiefgarageneinfahrt',
	parkingMulti: 'Eingang zu einem mehrstöckigen Parkhaus',
	christian: 'Christlich (außer Zeugen Jehovas)',
	jewish: 'Jüdisch',
	muslim: 'Muslim',
	taoist: 'Taoistisch',
	hindu: 'Hindu',
	buddhist: 'Buddhistisch',
	shinto: 'Schinto',
	sikh: 'Sikh',
	religion_und: 'Nicht spezifizierte oder andere Religion',
	plaque: 'Gedenktafel / Blaue Plakette',
	statue: 'Statue',
	stone: 'Gedenkstein',
	bust: 'Büste',
	guidepost: 'Wegweiser',
	infoBoard: 'Informationstafel',
	infoMap: 'Tafel mit Karte',
	infoMap3d: 'Informationskarte als 3D-Modell',
	infoOffice: 'Tourismus-Information',
	infoTerminal: 'Informationsterminal',
	audioguide: 'Audioguide',
	embassy: 'Botschaft',
	consulate: 'Konsulat',
	swimmingArea: 'Schwimmbereich / (Innen- oder Außen-) Schwimmbad',
  waterPark: 'Wasserpark / Schwimmbereiche',
	noEntrance: 'Jede Tür eines Gebäudes, zu der der Zutritt nicht gestattet ist',
	palace: 'Schloss',
	stately: 'Herrschaftliches Haus',
	manor: 'Herrenhaus',
	castle: 'Burg',
	defensive: 'Verteidigungsburg',
	fortress: 'Verteidigungsburg / Festung',
	castrum: 'Verteidigungsburg / Castra',
	shiro: 'Verteidigungsburg / Shiro',
	kremlin: 'Kreml',
	wheelchair_yes: 'Rollstühle haben vollen, uneingeschränkten Zugang',
	wheelchair_limited: 'Rollstühle haben teilweise Zugang',
	wheelchair_no: 'Rollstühle haben KEINEN uneingeschränkten Zugang',
	wheelchair_designated: 'Der Weg oder Bereich ist für Rollstühle bestimmt oder speziell dafür gebaut',
	wheelchair_und: 'Der Zugang ist nicht definiert.',
	smoking_dedicated: 'Den Rauchern gewidmet; z.B. Raucherclub, Fumoir oder Coffeshop.',
	smoking_yes: 'Das Rauchen ist in der gesamten Immobilie erlaubt.',
	smoking_separated: 'Das Rauchen ist in einem abgetrennten Bereich erlaubt.',
	smoking_isolated: 'Das Rauchen ist in einem abgetrennten Raum erlaubt.',
	smoking_no: 'Das Rauchen ist in der gesamten Immobilie verboten, ohne Ausnahmen.',
	smoking_outside: 'Rauchen ist auf dem Grundstück erlaubt, aber nur in Außenbereichen.',
	smoking_und: 'Keine Infos zum Rauchen.',
	public_yes: 'Öffentlicher Zugang',
	public_no: 'Keine öffentliche Besucher',
	free_yes: 'Gratis-Zugang',
	free_no: 'Kostenpflichtig',
	maxCapacity: 'max. Kapazität'
};
