export default {
	calendar: 'Kalendar',
	locationmap: 'Veranstaltungsort',
	event: 'Veranstaltung',
	eventInLang: 'Veranstaltung in',
	cancelled: 'Abgesagt',
	postponed: 'Aufgeschoben',
	rescheduled: 'Verlegt auf',
	movedOnline: 'Nur online',
	onlineEvent: 'Virtuelle Veranstaltung',
	offlineEvent: 'Persönliche Veranstaltung',
	mixedEvent: 'Hybride Veranstaltung (on-/offline)',
	onlineShort: 'online',
	offlineShort: 'offline',
	mixedShort: 'hybrid',
	updated: 'geändert',
	tba: 'wird angekündigt',
	previousStartDate: 'vorheriges Datum war',
	moreInfo: 'Weiterführende Informationen'
};
