export default {
	Accept: "Akzeptieren",
	Activity: "Aktivität",
	Add: "Hinzufügen",
	Announce: "Teilen",
	Application: "Anwendung",
	Arrive: "Ankommen",
	Article: "Artikel",
	Audio: "Audio",
	Block: "Blockieren",
	Collection: "Sammlung",
	CollectionPage: "Seite einer Sammlung",
	Create: "Erstellen",
	Delete: "Löschen",
	Dislike: "Nicht mehr mögen",
	Document: "Dokument",
	Event: "Ereignis",
	Flag: "Flag",
	Follow: "Folgen",
	Group: "Gruppe",
	Ignore: "Ignorieren",
	Image: "Bild",
	Invite: "Einladung",
	Join: "Beitreten",
	Leave: "Verlassen",
	Like: "Mögen",
	Link: "Link",
	Listen: "Hören",
	Mention: "Erwähnung",
	Move: "Verschieben",
	Note: "Notiz",
	Object: "Objekt",
	Offer: "Angebot",
	OrderedCollection: "Geordnete Sammlung",
	OrderedCollectionPage: "Seite einer geordneten Sammlung",
	Organization: "Organisation",
	Page: "Seite",
	Person: "Person",
	Place: "Platz",
	Profile: "Profil",
	Question: "Frage",
	Read: "Lesen",
	Reject: "Ablehnen",
	Relationship: "Beziehung",
	Remove: "Entfernen",
	Service: "Service",
	TentativeAccept: "Vermutlich Akzeptieren",
	TentativeReject: "Vermutlich Ablehnen",
	Tombstone: "Tombstone",
	Travel: "Reise",
	Undo: "Undo",
	Update: "Update",
	Video: "Video",
	View: "Ansehen",
	accuracy: "Präzision",
	actor: "Akteur",
	attachment: "Anhang",
	attributedTo: "zugeschrieben",
	audience: "Publikum",
	current: "momentan",
	describes: "beschreibt",
	duration: "Dauer",
	endTime: "Ende",
	first: "erste",
	height: "Höhe",
	image: "Bild",
	instrument: "Instrument",
	items: "Einträge",
	last: "letzte",
	location: "Örtlichkeit",
	next: "nächste",
	prev: "vorherige",
	preview: "Vorschau",
	published: "veröffentlicht",
	relationship: "Beziehung",
	replies: "Antworten",
	result: "Resultat",
	startTime: "Start",
	subject: "Betreff",
	updated: "aktualisiert",
	width: "Breite",
	_of: 'von',
	_in: 'in'
};
